package lib

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// TerraformGenerator handles the generation of Terraform files
type TerraformGenerator struct {
	outputDir      string
	config         *Config
	resources      []TerraformResource
	importCommands []ImportCommand
}

// NewTerraformGenerator creates a new Terraform generator
func NewTerraformGenerator(outputDir string, config *Config) *TerraformGenerator {
	return &TerraformGenerator{
		outputDir:      outputDir,
		config:         config,
		resources:      make([]TerraformResource, 0),
		importCommands: make([]ImportCommand, 0),
	}
}

// AddResource adds a resource to be generated and queues terraform import
func (tg *TerraformGenerator) AddResource(resourceType, name string, attributes map[string]any) {
	// Extract and store the ID separately
	var resourceID string
	if id, exists := attributes["id"]; exists {
		if idStr, ok := id.(string); ok {
			resourceID = idStr
		}
	}

	tg.resources = append(tg.resources, TerraformResource{
		Type:       resourceType,
		Name:       name,
		Attributes: attributes,
		IsData:     false,
		ID:         resourceID,
	})
	fmt.Printf("  Added %s resource: %s\n", resourceType, name)

	// Queue terraform import for this resource
	tg.QueueImport(resourceType, name, resourceID)
}

// AddResourceNoImport adds a resource that has no importable ID, such as the
// account-wide netbird_dns_settings singleton.
func (tg *TerraformGenerator) AddResourceNoImport(resourceType, name string, attributes map[string]any) {
	tg.resources = append(tg.resources, TerraformResource{
		Type:       resourceType,
		Name:       name,
		Attributes: attributes,
		IsData:     false,
	})
	fmt.Printf("  Added %s resource: %s (no import)\n", resourceType, name)
}

// AddDataSource adds a data source to be generated
func (tg *TerraformGenerator) AddDataSource(dataType, name string, attributes map[string]any) {
	tg.resources = append(tg.resources, TerraformResource{
		Type:       dataType,
		Name:       name,
		Attributes: attributes,
		IsData:     true,
	})
	fmt.Printf("  Added %s data source: %s\n", dataType, name)
}

// QueueImport queues a terraform import command
func (tg *TerraformGenerator) QueueImport(resourceType, name string, resourceID string) {
	if resourceID == "" {
		fmt.Printf("  Warning: No ID found for %s resource %s, skipping terraform import\n", resourceType, name)
		return
	}

	resourceAddress := fmt.Sprintf("netbird_%s.%s", resourceType, name)

	tg.importCommands = append(tg.importCommands, ImportCommand{
		ResourceAddress: resourceAddress,
		ResourceID:      resourceID,
	})

	fmt.Printf("  Queued terraform import for %s\n", resourceAddress)
}

// GetImportCommands returns the list of import commands
func (tg *TerraformGenerator) GetImportCommands() []ImportCommand {
	return tg.importCommands
}

// GetResources returns the list of resources
func (tg *TerraformGenerator) GetResources() []TerraformResource {
	return tg.resources
}

// WriteResource writes a single resource or data source to the file
func (tg *TerraformGenerator) WriteResource(file *os.File, resource TerraformResource) error {
	// Write resource or data source block
	if resource.IsData {
		fmt.Fprintf(file, "data \"netbird_%s\" \"%s\" {\n", resource.Type, resource.Name)
	} else {
		fmt.Fprintf(file, "resource \"netbird_%s\" \"%s\" {\n", resource.Type, resource.Name)
	}

	// Write attributes
	for _, key := range SortedKeys(resource.Attributes) {
		err := tg.writeAttribute(file, key, resource.Attributes[key], 1)
		if err != nil {
			return err
		}
	}

	fmt.Fprintf(file, "}\n")
	return nil
}

// WriteResourceFile writes resources to a specific file
func (tg *TerraformGenerator) WriteResourceFile(resourceType string, resources []TerraformResource) error {
	filename := filepath.Join(tg.outputDir, fmt.Sprintf("%s.tf", resourceType))
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	// Write file header
	fmt.Fprintf(file, "# NetBird %s resources\n# Generated by NetBird terraformer Terraformer\n\n", resourceType)

	// Sort a copy so the file order does not depend on the order the NetBird API
	// happened to return, and the caller's slice is left untouched.
	sorted := make([]TerraformResource, len(resources))
	copy(sorted, resources)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].Name < sorted[j].Name
	})

	// Write each resource
	for _, resource := range sorted {
		err := tg.WriteResource(file, resource)
		if err != nil {
			return err
		}
		fmt.Fprintf(file, "\n")
	}

	return nil
}

// writeAttribute writes an attribute to the file with proper formatting
func (tg *TerraformGenerator) writeAttribute(file *os.File, key string, value any, indent int) error {
	// Skip read-only fields in Terraform. Only at the top level: inside nested
	// blocks such as source_resource / destination_resource, "id" identifies the
	// referenced resource and must be written.
	//
	// "peers" is skipped deliberately rather than because it is read-only: it is
	// optional+computed on netbird_group, so it is writable. Peer membership is
	// derived server-side from each user's auto_groups (see user.tf) with
	// groups_propagation_enabled, so writing it here would fight that.
	if indent == 1 && (key == "id" || key == "network_type" || key == "peers") {
		return nil
	}

	indentStr := strings.Repeat("  ", indent)

	switch v := value.(type) {
	case string:
		if v != "" {
			fmt.Fprintf(file, "%s%s = \"%s\"\n", indentStr, key, EscapeString(v))
		}
	case ForceString:
		fmt.Fprintf(file, "%s%s = \"%s\"\n", indentStr, key, EscapeString(string(v)))
	case bool:
		fmt.Fprintf(file, "%s%s = %t\n", indentStr, key, v)
	case int, int64, float64:
		fmt.Fprintf(file, "%s%s = %v\n", indentStr, key, v)
	case RawValue:
		fmt.Fprintf(file, "%s%s = %s\n", indentStr, key, string(v))
	case ObjectValue:
		if len(v) == 0 {
			return nil
		}
		fmt.Fprintf(file, "%s%s = {\n", indentStr, key)
		for _, k := range SortedKeys(v) {
			err := tg.writeAttribute(file, k, v[k], indent+1)
			if err != nil {
				return err
			}
		}
		fmt.Fprintf(file, "%s}\n", indentStr)
	case ObjectList:
		if len(v) == 0 {
			return nil
		}
		fmt.Fprintf(file, "%s%s = [\n", indentStr, key)
		for _, item := range v {
			fmt.Fprintf(file, "%s  {\n", indentStr)
			for _, k := range SortedKeys(item) {
				err := tg.writeAttribute(file, k, item[k], indent+2)
				if err != nil {
					return err
				}
			}
			fmt.Fprintf(file, "%s  },\n", indentStr)
		}
		fmt.Fprintf(file, "%s]\n", indentStr)
	case []any:
		if len(v) > 0 {
			// Check if this is a list of maps (like rules)
			if len(v) > 0 {
				if _, isMap := v[0].(map[string]any); isMap {
					// Handle as blocks (e.g., rules blocks)
					for _, item := range v {
						if itemMap, ok := item.(map[string]any); ok {
							// Use singular form for block name
							blockName := GetBlockName(key)
							fmt.Fprintf(file, "%s%s {\n", indentStr, blockName)
							for _, k := range SortedKeys(itemMap) {
								err := tg.writeAttribute(file, k, itemMap[k], indent+1)
								if err != nil {
									return err
								}
							}
							fmt.Fprintf(file, "%s}\n", indentStr)
						}
					}
					return nil
				}
			}

			// Handle as regular list
			fmt.Fprintf(file, "%s%s = [\n", indentStr, key)
			for _, item := range v {
				switch str := item.(type) {
				case RawValue:
					// A resolved reference such as data.netbird_peer.foo.id.
					// Without this case the item matched nothing below and was
					// dropped silently, emptying the list.
					fmt.Fprintf(file, "%s  %s,\n", indentStr, string(str))
				case string:
					if str == "" {
						continue
					}
					// Check if this is a Terraform reference (starts with netbird_)
					if strings.HasPrefix(str, "netbird_") {
						// Output without quotes for Terraform references
						fmt.Fprintf(file, "%s  %s,\n", indentStr, str)
					} else {
						fmt.Fprintf(file, "%s  \"%s\",\n", indentStr, EscapeString(str))
					}
				default:
					return fmt.Errorf("unsupported %s list item of type %T", key, item)
				}
			}
			fmt.Fprintf(file, "%s]\n", indentStr)
		}
	case []string:
		if len(v) > 0 {
			fmt.Fprintf(file, "%s%s = [\n", indentStr, key)
			for _, item := range v {
				if item != "" {
					// Check if this is a Terraform reference
					if strings.HasPrefix(item, "netbird_") {
						// Output without quotes for Terraform references
						fmt.Fprintf(file, "%s  %s,\n", indentStr, item)
					} else {
						fmt.Fprintf(file, "%s  \"%s\",\n", indentStr, EscapeString(item))
					}
				}
			}
			fmt.Fprintf(file, "%s]\n", indentStr)
		}
	case map[string]any:
		fmt.Fprintf(file, "%s%s {\n", indentStr, key)
		for _, k := range SortedKeys(v) {
			err := tg.writeAttribute(file, k, v[k], indent+1)
			if err != nil {
				return err
			}
		}
		fmt.Fprintf(file, "%s}\n", indentStr)
	}

	return nil
}

// GenerateProviderFile generates the provider.tf file
func (tg *TerraformGenerator) GenerateProviderFile() error {
	// Create output directory
	err := os.MkdirAll(tg.outputDir, 0755)
	if err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	filename := filepath.Join(tg.outputDir, "provider.tf")
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	// The token is never written to disk: it is passed at runtime through
	// TF_VAR_netbird_token so it cannot leak into the repository.
	const providerConfig = `# NetBird Terraform Provider Configuration
# Generated by NetBird Terraformer

terraform {
  backend "http" {}

  required_providers {
    netbird = {
      source  = "netbirdio/netbird"
      version = "0.0.10"
    }
  }
}

provider "netbird" {
  management_url = var.netbird_management_url
  token          = var.netbird_token
}
`

	fmt.Fprint(file, providerConfig)
	return nil
}

// GenerateVariablesFile generates the variables.tf file backing provider.tf
func (tg *TerraformGenerator) GenerateVariablesFile() error {
	err := os.MkdirAll(tg.outputDir, 0755)
	if err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	filename := filepath.Join(tg.outputDir, "variables.tf")
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintf(file, `variable "netbird_management_url" {
  description = "Netbird management server URL"
  type        = string
  default     = %q
}

variable "netbird_token" {
  description = "Netbird API token"
  type        = string
  sensitive   = true
}
`, tg.config.ServerURL)

	return nil
}

// GenerateClustersFile writes clusters.tf: the reverse proxy cluster data
// source plus a lookup map keyed by address.
//
// Clusters are provisioned outside Terraform and the provider ships no matching
// resource, so they can only be read. Domains reference this map instead of
// hardcoding a cluster address, which turns a decommissioned or renamed cluster
// into a plan-time failure rather than a silent retarget.
func (tg *TerraformGenerator) GenerateClustersFile() error {
	err := os.MkdirAll(tg.outputDir, 0755)
	if err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	filename := filepath.Join(tg.outputDir, "clusters.tf")
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprint(file, `# NetBird reverse proxy clusters
# Generated by NetBird terraformer Terraformer
#
# Association happens at the DOMAIN level, not the service level:
# netbird_reverse_proxy_service.proxy_cluster is computed-only and cannot be
# assigned, so a service inherits the cluster of its domain. Putting services on
# different clusters means pointing their domains at different clusters.
#
# The data source exposes only address and connected_proxies -- the cluster id,
# name and type are in the API but not surfaced by the provider, so address is
# the only usable key.
data "netbird_reverse_proxy_clusters" "available" {}

locals {
  proxy_clusters = {
    for c in data.netbird_reverse_proxy_clusters.available.clusters : c.address => c
  }
}
`)

	return nil
}

// GenerateImportBlocks writes imports.tf with a Terraform import block per
// resource. Unlike the import script, these show up in terraform plan, so the
// whole import can be reviewed before anything is written to the state.
func (tg *TerraformGenerator) GenerateImportBlocks() error {
	if len(tg.importCommands) == 0 {
		return nil
	}

	filename := filepath.Join(tg.outputDir, "imports.tf")
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	commands := make([]ImportCommand, len(tg.importCommands))
	copy(commands, tg.importCommands)
	sort.Slice(commands, func(i, j int) bool {
		return commands[i].ResourceAddress < commands[j].ResourceAddress
	})

	fmt.Fprintf(file, "# NetBird import blocks\n")
	fmt.Fprintf(file, "# Generated by NetBird terraformer Terraformer\n")
	fmt.Fprintf(file, "#\n")
	fmt.Fprintf(file, "# Run terraform plan to review, then apply to bind these existing\n")
	fmt.Fprintf(file, "# resources to the state. Delete this file once the import is done.\n\n")

	for _, cmd := range commands {
		fmt.Fprintf(file, "import {\n")
		fmt.Fprintf(file, "  to = %s\n", cmd.ResourceAddress)
		fmt.Fprintf(file, "  id = %q\n", cmd.ResourceID)
		fmt.Fprintf(file, "}\n\n")
	}

	fmt.Printf("Generated imports.tf with %d import blocks\n", len(commands))
	return nil
}

// GenerateImportScript generates a script with all terraform import commands
func (tg *TerraformGenerator) GenerateImportScript() error {
	if len(tg.importCommands) == 0 {
		return nil
	}

	scriptPath := filepath.Join(tg.outputDir, "import.sh")
	file, err := os.Create(scriptPath)
	if err != nil {
		return err
	}
	defer file.Close()

	err = os.Chmod(scriptPath, 0755)
	if err != nil {
		return err
	}

	fmt.Fprintln(file, "#!/bin/bash")
	fmt.Fprintln(file, "# NetBird Terraform Import Script")
	fmt.Fprintln(file, "# Generated by NetBird terraformer Terraformer")
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "set -e")
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "echo \"Running terraform init...\"")
	fmt.Fprintln(file, "terraform init")
	fmt.Fprintln(file, "")
	fmt.Fprintln(file, "echo \"Running terraform imports...\"")

	// Sort a copy so the script does not change with the order the API replied in.
	commands := make([]ImportCommand, len(tg.importCommands))
	copy(commands, tg.importCommands)
	sort.Slice(commands, func(i, j int) bool {
		return commands[i].ResourceAddress < commands[j].ResourceAddress
	})

	for _, cmd := range commands {
		fmt.Fprintf(file, "echo \"Importing %s...\"\n", cmd.ResourceAddress)
		fmt.Fprintf(file, "terraform import \"%s\" \"%s\"\n", cmd.ResourceAddress, cmd.ResourceID)
		fmt.Fprintln(file, "")
	}

	fmt.Fprintln(file, "echo \"All imports completed!\"")
	fmt.Fprintln(file, "echo \"formatting files...\"")
	fmt.Fprintln(file, "terraform fmt")

	return nil
}

// GroupMapping represents a group mapping for JSON output
type GroupMapping struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	ResourceName string `json:"terraform_resource_name"`
}

// GenerateGroupMapping generates a JSON file with group mappings
func (tg *TerraformGenerator) GenerateGroupMapping() error {
	mappings := make([]GroupMapping, 0)

	for _, resource := range tg.resources {
		if resource.Type == "group" {
			if name, exists := resource.Attributes["name"]; exists {
				if nameStr, ok := name.(string); ok {
					mappings = append(mappings, GroupMapping{
						ID:           "<!-- ID will be available after terraform apply -->",
						Name:         nameStr,
						ResourceName: resource.Name,
					})
				}
			}
		}
	}

	mappingPath := filepath.Join(tg.outputDir, "group_mappings.json")
	file, err := os.Create(mappingPath)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Fprintln(file, "{")
	fmt.Fprintln(file, "  \"_note\": \"To get actual group IDs, run 'terraform show' after 'terraform apply'\",")
	fmt.Fprintln(file, "  \"_usage\": \"Use netbird_group.<resource_name>.id in auto_groups for new users\",")
	fmt.Fprintln(file, "  \"groups\": [")

	for i, mapping := range mappings {
		fmt.Fprintf(file, "    {\n")
		fmt.Fprintf(file, "      \"name\": %q,\n", mapping.Name)
		fmt.Fprintf(file, "      \"terraform_resource\": %q,\n", mapping.ResourceName)
		fmt.Fprintf(file, "      \"terraform_reference\": \"netbird_group.%s.id\"\n", mapping.ResourceName)
		if i < len(mappings)-1 {
			fmt.Fprintf(file, "    },\n")
		} else {
			fmt.Fprintf(file, "    }\n")
		}
	}

	fmt.Fprintln(file, "  ]")
	fmt.Fprintln(file, "}")

	return nil
}

// TerraformInit runs terraform init in the specified directory
func TerraformInit(folderPath string) error {
	cmd := exec.Command("terraform", "init")
	cmd.Dir = folderPath

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

// TerraformImport runs terraform import for a specific resource
func TerraformImport(folderPath string, resourceAddress string, resourceID string) error {
	cmd := exec.Command("terraform", "import", resourceAddress, resourceID)
	cmd.Dir = folderPath

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}
